### ISSUE TITLE
Autogtp 6 resign not handled

### ISSUE THREAD

**Issue by tterava** [fsparv/LeelaWatcher#13]
In autogtp v6 leela sometimes resigns, which is not handled by the parser and causes a crash.

**Comment by fsparv** [comment]
Ah lovely yes, this wasn't a case that had to be handled previously...

**Comment by fsparv** [comment]
```
 358 (T12) 	Move:T12
 359 (resign) 	Move:resign
oh noes!!!
java.lang.RuntimeException: BAD MOVE: resign
	at leelawatcher.parser.AutoGtpOutputParser.parseMove(AutoGtpOutputParser.java:129)
	at leelawatcher.parser.AutoGtpOutputParser.lambda$start$0(AutoGtpOutputParser.java:90)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by fsparv** [comment]
Now handled in release 1.0.2 (https://github.com/fsparv/LeelaWatcher/releases/tag/REL_1_0_2)
