### ISSUE TITLE
Allow "resign" move

### ISSUE THREAD

**Issue by vrpolak** [fsparv/LeelaWatcher#16]
From what I can see, leela-zero could always output "resign" as a move. But looking at Pattern MOVE, that was never understood as a legal move by LeelaWatcher.
Probably, the earlier networks were not prone to resigning, but now they are, which leads to:

 255 (resign)   Move:resign
oh noes!!!
java.lang.RuntimeException: BAD MOVE: resign
        at leelawatcher.parser.AutoGtpOutputParser.parseMove(AutoGtpOutputParser.java:129)
        at leelawatcher.parser.AutoGtpOutputParser.lambda$start$0(AutoGtpOutputParser.java:90)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by vrpolak** [comment]
Nevermind, I have not noticed Issue #13.
